export { default as getActiveKey } from './getActiveKey'
export { default as getKeySize } from './getKeySize'
export { default as getListOfWords } from './getListOfWords'
export { default as playAudio } from './playAudio'
export { default as getPlotterOptions } from './getPlotterOptions'
export { default as calcPresition } from './calcPresition'
export { default as getPersonalBest } from './getPersonalBest'